# Generated by Django 5.1.1 on 2024-09-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=80)),
                ('edad', models.IntegerField(max_length=80)),
            ],
        ),
    ]
