# Generated by Django 5.1.1 on 2024-09-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_eneagrama_alter_usuario_edad_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
    ]
