# Generated by Django 5.1.1 on 2024-09-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_apellido_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=80),
        ),
    ]
