# Generated by Django 5.1.1 on 2024-09-24 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_posteo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
    ]
