# Generated by Django 5.1.1 on 2024-09-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_posteo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_eneagrama',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
    ]
